### ISSUE TITLE
setEventDataProvider

### ISSUE THREAD

**Issue by arunramya** [p-v/FlexibleCalendar#43]
Called mutiple times please answer me ?

**Comment by p-v** [comment]
Yes it is called multiple times, because it is called for each cell in the view. There are three views at a time i.e. left, right and center. It is called for all the cells in those three views. It will also be called when you scroll left of right. It is used to tell if the cell with that particular `year, month, day` has any events or not. You should make sure that you are not doing any heavy lifting jobs there. Its used to set the events and is being used in the cell views. I hope this clears your confusion.

Read [here](https://gitter.im/p-v/FlexibleCalendar?at=56cee700dbccfd8a4fd05962) for more info.
